version: '3.4'

services:
    catalogdb:
        image: postgres:16.2-alpine

    basketdb:
        image: postgres:16.2-alpine

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
    postgres_catalog:
    postgres_basket: