version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=CatalogDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - postgres_catalog:/var/lib/postgresql/data/

  basketdb:
    container_name: basketdb
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=BasketDb
    restart: always
    ports:
        - "5433:5432"
    volumes:
        - postgres_basket:/var/lib/postgresql/data/ 

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ASPNETCORE_Kestrel__Certificates__Default__Password=
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/361CE3130C926E912B37F4448321C37ADAB9F09F.pfx
    depends_on:
      - catalogdb
    ports:
      - "6060:8081"
    volumes:
      - ~/.dotnet/corefx/cryptography/x509stores/my:/https:ro

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - ASPNETCORE_Kestrel__Certificates__Default__Password=
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/361CE3130C926E912B37F4448321C37ADAB9F09F.pfx
    depends_on:
      - basketdb
      - distributedcache
    ports:
      - "6061:8081"
    volumes:
      - ~/.dotnet/corefx/cryptography/x509stores/my:/https:ro

  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=Data Source=discountdb
      - ASPNETCORE_Kestrel__Certificates__Default__Password=
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/361CE3130C926E912B37F4448321C37ADAB9F09F.pfx
    ports:
      - "6062:8081"
    volumes:
      - ~/.dotnet/corefx/cryptography/x509stores/my:/https:ro